export const path = {
  HOME: '/',
  CHAT: '/chat',
  SHOP: '/shop',
  DONATIONS: '/donations',
  DONATION_DETAILS:'/donation-details',
  EVENTS: '/events',
  EVENTS_DETAILS: '/event_details',
  SOCIAL: '/social',
  SOCIAL_DETAIL: '/social/:id',
  GOSSIP: '/gossips',
  PRODUCT: '/product',
  SERVICES: '/services',
  SERVICES_DETAIL: '/services/:id',
  USER_MANAGEMENT: '/user-management',
  VENDOR_MANAGEMENT: '/vendor-management',
  VENDOR_MANAGEMENT_BOOKINGS: '/vendor-management-bookings',
  VENDOR_MANAGEMENT_DONATIONS: '/vendor-management-donations',
  VIEW_VENDOR_MANAGEMENT_DONATIONS: '/view-vendor-management-donations',
  VENDOR_MANAGEMENT_EVENTS: '/vendor-management-events',
};
