export const path = {
  HOME: '/',
  CHAT: '/chat',
  SHOP: '/shop',
  DONATIONS: '/donations',
  DONATION_DETAILS:'/donation-details',
  EVENTS: '/events',
  EVENTS_DETAILS: '/event_details',
  SOCIAL: '/social',
  SOCIAL_DETAIL: '/social/:id',
  GOSSIP: '/gossips',
  PRODUCT: '/product',
  SERVICES: '/services',
  SERVICES_DETAIL: '/services/:id',
  DONATION_USER_MANAGEMENT: '/user-management-donation',
  POINT_USER_MANAGEMENT: '/user-management-points',
  BOOKINGS_USER_MANAGEMENT: '/user-management-bookings',
  REWARD_USER_MANAGEMENT: '/user-management-reward',
  TICKET_USER_MANAGEMENT: '/user-management-ticket',
  NIGERIA_LOCAL_GOVERNMENT: '/nigeria_local_government',
  NIGERIA_DOMICIALLY_ACCOUNT: '/nigeria_domicially_account',
  US_ACCOUNT: '/us_account',
  SHARE_POINTS: '/share-points',
  BUY_MORE_POINTS: '/buy-more-points',

};
